// lib/content/about.ts
// Generated by scripts/scrape-seed.ts — source: top10prom.com/t7/about-us.html
// Generated: 2026-03-04T23:16:29.983Z

export const ABOUT_PARAGRAPHS: string[] = [
  `At Top10prom.com, we're not just the biggest network of prom dress retailers in the US — we're your first step towards a night to remember. Owned and operated in the USA, we're here to guide you to the nearest store stocked with your dream dress. No nearby store? No problem! We're all set to help you find that perfect gown online.`,
  `Why Shop with Us? Imagine a place where every prom dress is a show-stopper. That's Top 10 Prom for you! We're known for our outstanding customer service, vast access to exclusive designs, and our knack for finding those one-of-a-kind, hard-to-find dresses. We're part of a global buying group, which means we bring you the best selections at unbeatable prices.`,
  `Discover Dresses That Dazzle Step out in style with our exclusive, cutting-edge designs. Whether you're on the hunt for a sequined ball gown that sparkles, a sleek two-piece that makes a statement, or a chic, affordable little black dress, we have it all. Our designers are magicians with fabric, creating everything from enchanting lace details to trendy boho chic looks. And if you're budget-conscious, check out our sexy, inexpensive prom dresses. Ready to lead the fashion parade? Our doors are open with the hottest trends just waiting to be discovered.`,
  `Find Your Nearest Store Got questions? Need specifics? Swing by your closest Top 10 Prom store and let's make your prom dream come true. Click to find a Top 10 Store!`,
  `Join Our Fabulous Network Do you own a retail store and wish to sprinkle some Top 10 magic onto your racks? Learn more about how you can join our vibrant network of prom retailers. [Contact Us Here Link]`,
  `Stay ahead of ordinary fashion by choosing from our hot and innovative styles. We pride ourselves on our wide variety of exclusive, limited-edition dresses that can only be found at one of our Top 10 Prom stores. Our talented designers create elegant evening gowns and chic inexpensive dresses with eye-catching couture. Our fresh colors and exclusive designs come in a variety of styles and designs such as; dazzling, sequined ball gowns, classic two-piece dresses, lace designs, and gorgeous boho details. We also have vibrant "little black dress" prom wear, luxurious fabrics and trend-setting styles that will give you an awesome advantage at your next event. If you are on a tight budget our collection includes inexpensive, sexy prom dresses. We have mini prom dresses and short, black dresses. Our designer dresses for 2024 are ready too! Stay ahead of the trends by choosing from our hot and innovative styles. Each one of our designers has a talent`,
];

export const ABOUT_HEADLINE = "Where Style Meets Splendor";
export const ABOUT_SUBHEADLINE =
  "The nation's largest network of specialty prom and formal wear boutiques.";
